### ISSUE TITLE
`after_action` silently fails unless `require_atomic? false` set for an update action

### ISSUE THREAD

**Issue by oskar1233** [ash-project/ash#1314] opened 2024-07-16 07:38 UTC
**Describe the bug**
`with_hooks` isn't called unless `require_atomic? false` set for update action, even when changeset is valid and makes changes in DB.

**To Reproduce**
Create a resource with:
```
actions do
  update :update
end
```

And try updating it:
```
struct
|> Ash.Changeset.for_update(:update, params)
|> Ash.Changeset.after_action(fn _, _ -> raise "Crash me" end)
|> Ash.update()
```

**Expected behavior**
In this scenario I expected the `fn` to be called and the `raise` to interrupt the transaction; or if this isn't the expected behaviour, at least emit a warning about hooks not being called.

**Runtime**
 - 1.17.0
 - OTP 27
 - macOS
 - Ash 3.1.3
 - Ash postgres 2.0.12
 - Ash Phoenix 2.0.4

**Additional context**
I started digging through the code and noticed that `Ash.Actions.Update.commit`, which runs `Ash.Changeset.with_hooks` isn't run at all. Instead, `Ash.Actions.Update.Bulk.run` was fired (line 149). This made me start reading about atomics and I stumbled upon `require_atomic?` which turned out to be the solution.

**Comment by zachdaniel** [comment] 2024-07-16 09:51
Can you upgrade to the latest `ash/ash_postgres` versions? I believe this issue has been fixed since the versions you are on.

Will close for now, but we can reopen if that does not resolve the issue.

**Comment by oskar1233** [comment] 2024-07-16 12:40
Unfortunately exactly the same happens on:
- ash 3.2.0
- ash_postgres 2.1.6
- ash_sql 0.2.21

**Comment by oskar1233** [comment] 2024-07-16 13:43
https://github.com/oskar1233/ash-proj-bug

`helpdesk.ex`
```elixir
  def test do
    {:ok, ticket} = Ash.create(Helpdesk.Support.Ticket, %{subject: "test"})

    {:ok, updated_ticket} =
      ticket
      |> Ash.Changeset.for_update(:update, %{"subject" => "updated sub"})
      |> Ash.Changeset.after_action(fn _, _ ->
        raise "Fail"
      end)
      |> Ash.update()

    updated_ticket
  end
```

After running `Helpdesk.test` in `iex -S mix` I'd expect an exception to be returned and it goes through just fine.

Interestingly enough, it was failing before I installed `ash_postgres` and added data layer to the resource.

**Comment by zachdaniel** [comment] 2024-07-16 14:08
Thank you for the reproduction 🙇 . This is fixed in `main`. Will release in the next few days.

**Closed by zachdaniel** 2024-07-16 14:08 UTC
Labels: bug
