### ISSUE TITLE
elixir_sense plugin crashes

### ISSUE THREAD

**Issue by lukaszsamson** [ash-project/ash#762] opened 2023-10-31 15:58 UTC
**Describe the bug**
I noticed this stacktrace coming from Ash elixir_sense plugin in ElixirLS telemetry logs
```
an exception was raised:
    ** (UndefinedFunctionError) function Ash.Type.builtins_0 is undefined or private
        (ash 2.14.17) Ash.Type.builtins()
USER_PATH_elixir_sense_aliases.ex:38: Spark.ElixirSense.Types.find_custom_types_4
USER_PATH_elixir_sense_plugin.ex:366: Spark.ElixirSense.Plugin.option_values_4
USER_PATH_elixir_sense_plugin.ex:114: Spark.ElixirSense.Plugin.get_suggestions_4
USER_PATH_elixir_sense_providers_suggestion_generic_reducer.ex:41: ElixirSense.Providers.Suggestion.GenericReducer.reduce_6
        (elixir 1.15.4) <REDACTED: user-file-path>:4830: Enumerable.List.reduce_3
        (elixir 1.15.4) <REDACTED: user-file-path>:2564: Enum.reduce_while_3
USER_PATH_elixir_sense_providers_suggestion.ex:137: ElixirSense.Providers.Suggestion.find_6
```

**To Reproduce**
No idea. I don't use Ash

**Expected behavior**
The plugin should not inject errors into elixir_sense

**Runtime**
 - Elixir version: various
 - Erlang version: various
 - OS: various
 - Ash version: various
 - any related extension versions: ElixirLS 0.17.2+

**Additional context**
The error is pretty common, over 1k instances in 7 days

**Comment by jimsynz** [comment] 2023-10-31 20:05
Hi @lukaszsamson. Thanks for letting us know! Is there a way for us to see this happening?

**Comment by lukaszsamson** [comment] 2023-11-01 10:25
I don't have an idea how to trigger it an d I can't provide any more context. Since it happens on code completion I'd try editing ash files and observe ElixirLS output log. If you use VSCode https://github.com/elixir-lsp/vscode-elixir-ls#check-elixirls-output

**Comment by jimsynz** [comment] 2023-11-01 19:50
Thanks for the pointers.

**Comment by zachdaniel** [comment] 2023-11-13 22:31
@lukaszsamson you mentioned that you don't use Ash, but you also mentioned that you were editing Ash files. Is there a project somewhere you can push up that I could try this on? I can't currently reproduce it.

**Comment by lukaszsamson** [comment] 2023-11-13 23:03
I only suggested how you can try to reproduce this crash. I don't use Ash personally. The stacktrace comes from telemetry data.

**Comment by zachdaniel** [comment] 2023-11-13 23:04
Ah, okay I see what you mean when you say telemetry data. you mean you're getting reports of errors from other users applications?

**Comment by lukaszsamson** [comment] 2023-11-13 23:22
> you're getting reports of errors from other users applications?

Yes

**Comment by zachdaniel** [comment] 2023-11-13 23:30
Gotcha. TBH, I can't reproduce on the latest versions of the packages or the latest version of ElixirLS. My suspicion is that someone out there has a really old version of ash or spark or something like that. There isn't much we can do about where the actual errors come from since our code is called by elixir_sense, and without being able to reproduce it I won't be able to fix it. I'll close this since there isn't really anything to go off of, but hopefully if the person who is encountering this issue searches for it now they will find this, and see that we are looking for more details.

**Closed by zachdaniel** 2023-11-13 23:30 UTC
Labels: bug, needs review
