### ISSUE TITLE
Load returns an empty collection for many-to-many relation without loading the special `_join_assoc`

### ISSUE THREAD

**Issue by smt116** [ash-project/ash#435] opened 2022-10-28 08:54 UTC
**Describe the bug**

```elixir
iex(19)> App.Resources.SomeResource.get_by_actor(actor: my_user, load: [:accounts])
{:ok,
 #App.Resources.SomeResource<
   accounts: [],
   accounts_join_assoc: #Ash.NotLoaded<:relationship>,
   ...
 >}
iex(20)> App.Resources.SomeResource.get_current_pending_round_up(actor: my_user, load: [:accounts_join_assoc, :accounts])
{:ok,
 #App.Resources.SomeResource<
   accounts: [
     #App.Resources.Account<
       ...
     >,
     #App.Resources.Account<
       ...
     >
   ],
   ...
 >}
```

**Expected behavior**
The `accounts` in that example should be loaded without the special `accounts_join_assoc` key in `load` list. Or at least it should not resolve to an empty collection.

**Runtime**
```
elixir λ grep '"ash' mix.lock
  "ash": {:git, "https://github.com/ash-project/ash.git", "67814a216062cd1b1ee2444ea3b1832c1ee93e9a", []},
  "ash_admin": {:hex, :ash_admin, "0.6.0-rc.1", "219809419f399afd560c657e00f500cbee033ca25694a30a4c4ca22db518c21c", [:mix], [{:ash, "~> 2.0.0-rc.7", [hex: :ash, repo: "hexpm", optional: false]}, {:ash_phoenix, "~> 1.0.0-rc.0", [hex: :ash_phoenix, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 3.2", [hex: :phoenix_html, repo: "hexpm", optional: false]}, {:phoenix_live_view, "~> 0.17", [hex: :phoenix_live_view, repo: "hexpm", optional: false]}, {:surface, "~> 0.7", [hex: :surface, repo: "hexpm", optional: false]}], "hexpm", "a8be458e8da3cb18714dfb59351387dae77f18a0068f5d5e82374b17163ee5bf"},
  "ash_graphql": {:git, "https://github.com/ash-project/ash_graphql.git", "a873dfd6855a64be7357a4cd0c00448514455979", []},
  "ash_phoenix": {:hex, :ash_phoenix, "1.0.0-rc.0", "7c5d780c6ebf239977ec0a3f40675ee3f3a5d6eaa4f28a95b4bc6701b61bbd67", [:mix], [{:ash, "~> 2.0.0-rc.0", [hex: :ash, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.5.6 or ~> 1.6.0", [hex: :phoenix, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.14 or ~> 3.0", [hex: :phoenix_html, repo: "hexpm", optional: false]}, {:phoenix_live_view, "~> 0.15", [hex: :phoenix_live_view, repo: "hexpm", optional: false]}], "hexpm", "e47246d2c7630b68a0d78d12824d73cd57d0948fe59dab736c26f79bb68b0ff3"},
  "ash_postgres": {:hex, :ash_postgres, "1.0.0-rc.5", "5ac52817061a5629e5bddbaf1f7309b4d3173ba23755496c5bec56f5c33ae503", [:mix], [{:ash, "~> 2.0.0-rc.7", [hex: :ash, repo: "hexpm", optional: false]}, {:ecto, "~> 3.8", [hex: :ecto, repo: "hexpm", optional: false]}, {:ecto_sql, "~> 3.8", [hex: :ecto_sql, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:postgrex, ">= 0.0.0", [hex: :postgrex, repo: "hexpm", optional: false]}], "hexpm", "96d0077f6b337616e2866a5df7170b2a73fdc5330f6cdc983c11d03111037936"},
```

**Comment by zachdaniel** [comment] 2022-10-28 12:46
I see, so `get` I believe loads after the fact, using `api.load(...)` and I recently optimized many to many loads and that must not be tested. I will test that now and fix it :)

**Comment by zachdaniel** [comment] 2022-10-28 15:02
Interesting... @smt116 are those actions manual actions by chance?

**Comment by zachdaniel** [comment] 2022-10-28 15:08
I've got a test shownig this working in ash core locally currently (using a code interface and the `load` option, getting a single record), so there must be something different about my setup and yours.

**Comment by zachdaniel** [comment] 2022-10-30 13:11
Also would be good to confirm that accounts is/isn't a manual relationship.

**Comment by zachdaniel** [comment] 2022-10-30 13:11
Never mind, there is no such thing as a manual many to many relationship :)

**Comment by smt116** [comment] 2022-10-31 11:24
> I've got a test shownig this working in ash core locally currently (using a code interface and the load option, getting a single record), so there must be something different about my setup and yours.

Do you test it using PostgreSQL as a backend or some other engine (e.g., ETS)? Maybe it behaves differently depending on the database engine 🤔

**Comment by zachdaniel** [comment] 2022-10-31 13:17
Yeah you're probably right :) I was thinking this logic didn't switch on that, but I think it does now that you point it out.

**Comment by zachdaniel** [comment] 2022-10-31 18:18
🤔 still strange. Using latest ash_postgres, things also working fine...

https://github.com/ash-project/ash_postgres/blob/main/test/load_test.exs#L132

@smt116 can you spot a difference here?

**Comment by zachdaniel** [comment] 2022-11-01 17:37
Thanks! Sorry for the rocky road on this issue.

**Comment by smt116** [comment] 2022-11-04 08:33
It turned out I'm not able to easily upgrade all Ash packages because we are in dependency hell at the moment - we can't upgrade all our packages now 🙈. I guess it has been fixed in newer Ash (probably Ash Postgres?) version if this works as expected in tests. We can close this issue for now and I can readdress it in the future (once the app is up-to-date with all deps).

**Comment by zachdaniel** [comment] 2022-11-04 08:47
uh oh! Is your dependency hell related to Ash dependency versions? If so, perhaps there is something we can do to help?

**Comment by smt116** [comment] 2022-11-04 08:52
AFAIK, the root issue is old Oban that depends on older Ecto SQL. We use some pro features and I don't want to touch it as a part of the current huge re-architecture work. I guess this (dependencies) will be the first thing after the release.

**Comment by zachdaniel** [comment] 2022-11-04 15:05
Interesting...I could potentially cut a branch of ash_postgres that is compatible with your version of ecto, not much has changed, realisticaly.

**Comment by zachdaniel** [comment] 2022-11-15 05:31
I'm going to close this for now, primarily because it hasn't been reproduced. However, any issue along these lines would naturally be a very high priority.

**Closed by zachdaniel** 2022-11-15 05:31 UTC
Labels: bug

**Comment by zachdaniel** [comment] 2022-11-17 20:16
I was able to reproduce this on older versions of the ash package. Not sure exactly which version fixed it, but if you are reading this message your first step to resolve this issue should be to upgrade.
