### ISSUE TITLE
Add compile time check for `defined_for` in `code_interface`

### ISSUE THREAD

**Issue by arosenb2** [ash-project/ash#742] opened 2023-10-17 17:58 UTC
**Describe the bug**

**To Reproduce**
```elixir
defmodule Example.SomeEmbeddedResource do
  use Ash.Resource,
    data_layer: :embedded

  attributes do
    attribute :foo, :string, allow_nil?: false
  end

  code_interface do
    define :foo, action: :create
  end
end
```

**Expected behavior**
In order to have any use of `code_interface`, `define_for` has to be included, but right now it is an easy oversight due to not failing at compile time.

**Runtime**
Elixir version: 1.15.5
Erlang version: OTP 26.0.2
OS: MacOS 13.5.2
Ash version: 2.15.7

**Comment by pierrelegall** [comment] 2023-10-17 18:54
You should be interested by https://github.com/ash-project/ash/issues/638.

**Comment by zachdaniel** [comment] 2023-10-17 19:08
I'm going to close this as effectively a duplicate of #683 We will likely not make this option required on its own, but in conjunction with this PR: https://github.com/ash-project/ash/pull/715 the DX should be mostly solved.

**Closed by zachdaniel** 2023-10-17 19:08 UTC
Labels: bug, needs review
