### ISSUE TITLE
no FunctionClause matching when loading calculation

### ISSUE THREAD

**Issue by barnabasJ** [ash-project/ash#568] opened 2023-04-20 07:37 UTC
**Describe the bug**
Hi, somewhere between this commit de943509f73ff0c6ef3749feb3cc6ab6e4d99d2d and now, I started getting an error in one of my graphql queries.

```
[error] Task #PID<0.6039.0> started from #PID<0.6032.0> terminating
** (Ash.Error.Unknown) Unknown Error

Context: resolving data on calculate hotel_itinerary_items.sort_order
* Context: resolving data on calculate hotel_itinerary_items.sort_order

** (FunctionClauseError) no function clause matching in Ash.Actions.Read.run_query/6
  (ash 2.6.31) lib/ash/actions/read.ex:2208: Ash.Actions.Read.run_query(#Ash.Query<resource: Demo.Offer.Resources.ItineraryItem.HotelItineraryItem, filter: #Ash.Filter<id in ["0a23ede2-ff04-4636-949f-321f9c9a4314", "5e65f643-7463-4456-8d19-e46c370f7950"]>>, #Ecto.Query<from h0 in JdlEngine.Offer.Resources.ItineraryItem.HotelItineraryItem, as: 0, where: type(as(0).id, {:parameterized, Ash.Type.UUID.EctoType, []}) in [
  type(^"0a23ede2-ff04-4636-949f-321f9c9a4314", {:parameterized, Ash.Type.UUID.EctoType, []}),
  type(^"5e65f643-7463-4456-8d19-e46c370f7950", {:parameterized, Ash.Type.UUID.EctoType, []})
], select: merge(merge(h0, %{}), %{
  sort_order:
    type(
      fragment(
        "(select sort_order from offer_itinerary_item oii where id = ? and item_type = ?)",
        type(as(0).id, {:parameterized, Ash.Type.UUID.EctoType, []}),
        ^"h"
      ),
      {:parameterized, Ash.Type.Integer.EctoType, []}
    )
})>, %{actor: %{id: "App User", roles: [:admin]}, api: Demo.Support, authorize?: true, tenant: nil}, false, [], [])
  (ash 2.6.31) lib/ash/actions/read.ex:2697: Ash.Actions.Read.run_calculation_query/6
  (ash 2.6.31) lib/ash/actions/read.ex:1529: anonymous fn/14 in Ash.Actions.Read.calculation_dependency_requests/9
  (ash 2.6.31) lib/ash/engine/request.ex:1048: Ash.Engine.Request.do_try_resolve_local/4
  (ash 2.6.31) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
  (ash 2.6.31) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
  (ash 2.6.31) lib/ash/engine/engine.ex:719: Ash.Engine.advance_request/2
  (ash 2.6.31) lib/ash/engine/engine.ex:625: Ash.Engine.fully_advance_request/2
  (ash 2.6.31) lib/ash/engine/engine.ex:566: Ash.Engine.do_run_iteration/2
  (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 2.6.31) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
  (ash 2.6.31) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
  (ash 2.6.31) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
  (ash 2.6.31) lib/ash/actions/read.ex:173: Ash.Actions.Read.do_run/3
  (ash 2.6.31) lib/ash/actions/read.ex:96: Ash.Actions.Read.run/3
  (ash 2.6.31) lib/ash/api/api.ex:1349: Ash.Api.load!/4
  (ash_graphql 0.23.3) lib/graphql/dataloader.ex:318: Dataloader.Source.AshGraphql.Dataloader.run_batch/2
  (ash_graphql 0.23.3) lib/graphql/dataloader.ex:182: anonymous fn/2 in Dataloader.Source.AshGraphql.Dataloader.run_batches/1
  (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
  (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
  ```

I tried to look at it, but I  wasn't able to figure it out yet. 

After your change from today the error message is now: 

```
[error] Task #PID<0.25471.0> started from #PID<0.25464.0> terminating
** (Ash.Error.Unknown) Unknown Error

Context: resolving data on calculate countries
* Context: resolving data on calculate countries

** (RuntimeError) Assumption Failed
  (ash 2.6.31) lib/ash/actions/load.ex:400: Ash.Actions.Load.last_relationship!/2
  (ash 2.6.31) lib/ash/actions/load.ex:91: anonymous fn/2 in Ash.Actions.Load.attach_loads/2
  (elixir 1.14.3) lib/enum.ex:3264: anonymous fn/2 in Enum.sort_by/3
  (elixir 1.14.3) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
  (stdlib 4.2) maps.erl:411: :maps.fold_1/3
  (elixir 1.14.3) lib/enum.ex:2480: Enum.map/2
  (elixir 1.14.3) lib/enum.ex:3264: Enum.sort_by/3
  (ash 2.6.31) lib/ash/actions/load.ex:90: Ash.Actions.Load.attach_loads/2
  (stdlib 4.2) maps.erl:411: :maps.fold_1/3
  (ash 2.6.31) lib/ash/actions/read.ex:2506: Ash.Actions.Read.calc_temp_results/5
  (ash 2.6.31) lib/ash/actions/read.ex:2389: anonymous fn/10 in Ash.Actions.Read.calculation_request/14
  (ash 2.6.31) lib/ash/engine/request.ex:1048: Ash.Engine.Request.do_try_resolve_local/4
  (ash 2.6.31) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
  (ash 2.6.31) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
  (ash 2.6.31) lib/ash/engine/engine.ex:719: Ash.Engine.advance_request/2
  (ash 2.6.31) lib/ash/engine/engine.ex:625: Ash.Engine.fully_advance_request/2
  (ash 2.6.31) lib/ash/engine/engine.ex:566: Ash.Engine.do_run_iteration/2
  (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 2.6.31) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
  (ash 2.6.31) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
    (ash 2.6.31) lib/ash/actions/load.ex:400: Ash.Actions.Load.last_relationship!/2
    (ash 2.6.31) lib/ash/actions/load.ex:91: anonymous fn/2 in Ash.Actions.Load.attach_loads/2
    (elixir 1.14.3) lib/enum.ex:3264: anonymous fn/2 in Enum.sort_by/3
    (elixir 1.14.3) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (elixir 1.14.3) lib/enum.ex:2480: Enum.map/2
    (elixir 1.14.3) lib/enum.ex:3264: Enum.sort_by/3
    (ash 2.6.31) lib/ash/actions/load.ex:90: Ash.Actions.Load.attach_loads/2
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (ash 2.6.31) lib/ash/actions/read.ex:2506: Ash.Actions.Read.calc_temp_results/5
    (ash 2.6.31) lib/ash/actions/read.ex:2389: anonymous fn/10 in Ash.Actions.Read.calculation_request/14
    (ash 2.6.31) lib/ash/engine/request.ex:1048: Ash.Engine.Request.do_try_resolve_local/4
    (ash 2.6.31) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
    (ash 2.6.31) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
    (ash 2.6.31) lib/ash/engine/engine.ex:719: Ash.Engine.advance_request/2
    (ash 2.6.31) lib/ash/engine/engine.ex:625: Ash.Engine.fully_advance_request/2
    (ash 2.6.31) lib/ash/engine/engine.ex:566: Ash.Engine.do_run_iteration/2
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash 2.6.31) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
    (ash 2.6.31) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
Function: &:erlang.apply/2
    Args: [#Function<13.123878446/1 in Dataloader.Source.AshGraphql.Dataloader.run_batches/1>, [{{:calc, JdlEngine.Offer.Resources.ItineraryCollection, #PID<0.25439.0>, :countries, %{api_opts: [actor: %{id: "App User", roles: [:admin]}, authorize?: true, verbose?: true], args: %{}, resource: JdlEngine.Offer.Resources.ItineraryCollection, span_context: nil, tenant: nil, type: :calculation}}, MapSet.new([{["031d980e-3a7b-46d1-8149-48b678a860ed"], #Demo.Offer.Resources.ItineraryCollection<countries: #Ash.NotLoaded<:calculation>, travel_buddy_count: #Ash.NotLoaded<:calculation>, travel_events: #Ash.NotLoaded<:calculation>, margin_rate: #Ash.NotLoaded<:calculation>, margin: #Ash.NotLoaded<:calculation>, selling_price: #Ash.NotLoaded<:calculation>, target_buying_price: #Ash.NotLoaded<:calculation>, source_buying_price: #Ash.NotLoaded<:calculation>, has_villa: #Ash.NotLoaded<:calculation>, item_count: #Ash.NotLoaded<:aggregate>, travel_buddy_metrics: #Ash.NotLoaded<:relationship>, items: #Ash.NotLoaded<:relationship>, cruise_itinerary_items: #Ash.NotLoaded<:relationship>, villa_itinerary_items: #Ash.NotLoaded<:relationship>, hotel_itinerary_items: #Ash.NotLoaded<:relationship>, generic_itinerary_items: #Ash.NotLoaded<:relationship>, flight_itinerary_items: #Ash.NotLoaded<:relationship>, image: #Ash.NotLoaded<:relationship>, offer: #Ash.NotLoaded<:relationship>, flight_itinerary_items_join_assoc: #Ash.NotLoaded<:relationship>, generic_itinerary_items_join_assoc: #Ash.NotLoaded<:relationship>, hotel_itinerary_items_join_assoc: #Ash.NotLoaded<:relationship>, villa_itinerary_items_join_assoc: #Ash.NotLoaded<:relationship>, cruise_itinerary_items_join_assoc: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "offer_itinerary_collection">, updated_at: nil, created_at: nil, updated_by: nil, created_by: nil, id: "031d980e-3a7b-46d1-8149-48b678a860ed", name: "Bahi Del Duque", collection_nr: 1, offer_id: "740ccd3d-0373-4dd5-85c9-83b854fac584", public_notes: "", visibility: nil, sort_order: 0, terms_and_conditions: nil, sent_at: nil, aggregates: %{}, calculations: %{}, __order__: nil, ...>}])}]]
```

**To Reproduce**

It happens when the `:unkown` branch is executed here: https://github.com/ash-project/ash/blob/5005d57b1db3522a09accc6f10418ac230fe2c40/lib/ash/actions/read.ex#L1526

The context inside the query is empty and no action is set, therefore no run_query function matches.

The calulation it's trying to load is a simple `expr` calulcation with a `fragment` inside on a resource using AshPostgres Datalayer, no `args` are anything.

**Expected behavior**

It should load the calculation

**Runtime**
 - Elixir version 1.14.3
 - Erlang version 25.1
 - OS Ubuntu 22.04
 - Ash version main (commit: 84a426c53eec53a96e7ad15e0900aa90e8fc504e)
 - any related extension versions
   - ash_grapqhl commit: d4ee7c5
   - ash_postgres commit aec9e15

**Additional context**

**Comment by zachdaniel** [comment] 2023-04-20 13:48
I'm unable to reproduce so far, but I spotted a potential issue and have pushed a fix for it to main. Worth giving it a try to see if it resolves the issue.

**Comment by zachdaniel** [comment] 2023-04-20 14:02
Fix confirmed in main

**Closed by zachdaniel** 2023-04-20 14:02 UTC
Labels: bug
