### ISSUE TITLE
Change with before_action or before_tranaction hook not being enforced.

### ISSUE THREAD

**Issue by AJReade** [ash-project/ash#1218] opened 2024-06-01 21:29 UTC
**Describe the bug**
When trying to force a custom change in it's own module to run before an action, it is being run after.

The change
```elixir
use Ash.Resource.Change

def change(changeset, _opts, _context) do
    Ash.Changeset.before_transaction(changeset, &maybe_slugify_title/1)
  end

  def maybe_slugify_title(changeset) do
    case Ash.Changeset.get_attribute(changeset, :title) do
      title when is_binary(title) ->
        Ash.Changeset.change_new_attribute(changeset, :slug, Slug.slugify(title))

      _ ->
        changeset
    end
  end
```

The resource:
```elixir
attribute :slug, :string, public?: true, primary_key?: true

attribute :title, :string, public?: true

#action
 create :slugify do
      # change Glow.Lobby.Changes.Slugify
 end

```

When running:

```elixir
Glow.Lobby.Room
|> Ash.Changeset.for_create(:slugify, %{title: "The video room"})
```

Changeset is not updated:

```elixir
#Ash.Changeset<
  domain: Glow.Lobby,
  action_type: :create,
  action: :slugify,
  attributes: %{title: "hi"},
  relationships: %{},
  errors: [],
  data: #Glow.Lobby.Room<
    __meta__: #Ecto.Schema.Metadata<:built, "rooms">,
    slug: nil,
    title: nil,
    inserted_at: nil,
    updated_at: nil,
    aggregates: %{},
    calculations: %{},
    ...
  >,
  valid?: true
>
```

Output:

```elixir
** (Ash.Error.Invalid) Invalid Error

* attribute slug is required
  (elixir 1.16.2) lib/process.ex:860: Process.info/2

```

Okay looks like its making sense but when you remove all the ash protections by changing the resource but not migrating:
```elixir
 attribute :slug, :string, public?: true
```

output: 

```elixir
** (Ash.Error.Unknown) Unknown Error

* ** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "slug" of relation "rooms" violates not-null constraint

    table: rooms
    column: slug
```

**Expected behavior**

Change runs prior to action.

**Runtime**
 - Elixir version:  1.16.2-otp-26
 - Erlang version: 26.0.2
 - OS: Mac OS M1 14.0
 - Ash version: {:ash, "~> 3.0"},
 - any related extension versions:
```elixir      
      {:picosat_elixir, "~> 0.2"},
      {:ash_postgres, "~> 2.0"},
      {:ash_phoenix, "~> 2.0"},
      {:ash_authentication_phoenix, "~> 2.0"},
      {:ash_authentication, "~> 4.0"},
      {:ash_json_api, "~> 1.0"},
```

**Additional context**
Work around: 
```elixir
  # Slugify Before Action Hook not working use this for now
  def create_room(title) do
    Glow.Lobby.Room
    |> Ash.Changeset.new()
    |> Ash.Changeset.change_attributes(%{title: title})
    |> Glow.Lobby.Changes.Slugify.maybe_slugify_title()
    |> Ash.Changeset.for_create(:slugify)
    |> Ash.create!()
  end
```

**Comment by zachdaniel** [comment] 2024-06-02 15:59
I'm unfortunately unable to reproduce this. I've added tests to `ash` core in a recent commit the illustrate this exact functionality working as expected, so there has to be some factor that isn't represented, and the data layer shouldn't factor into this issue. I'll close this for now. If you could provide a repo or test that reproduces this issue, then I can address.

**Closed by zachdaniel** 2024-06-02 15:59 UTC
Labels: bug

**Comment by AJReade** [comment] 2024-06-03 13:19
No worries thanks for your time looking into this, I appreciate everything you do for the elixir community. Big ash fan!
