### ISSUE TITLE
has_many through

### ISSUE THREAD

**Issue by jechol** [ash-project/ash#898] opened 2024-02-16 01:34 UTC
**Is your feature request related to a problem? Please describe.**
When I have three resources,

1. Country, which has_many States.
2. State, which has_many Cities.
3. City.

There is no straightforward way to load all the Cities corresponding to a Country.

**Describe the solution you'd like**
I want Country to has_many Cities through State.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```elixir
defmodule Country do
  relationships do
    has_many :states, State
    has_many :cities, City, through: :states, destination_relationship: :cities
  end
end

country |> Api.load([:states, :cities])
```

**Comment by zachdaniel** [comment] 2024-02-16 04:24
Duplicate of https://github.com/ash-project/ash/issues/72

**Closed by zachdaniel** 2024-02-16 04:24 UTC
Labels: enhancement, needs review

**Comment by vonagam** [comment] 2024-02-16 12:42
By the way, I assume that the OP knows but for others who might stumble here - this will do:
```elixir
country |> Api.load([states: :cities])
```
`cities` will be present on `states`, not directly on `country`. Also if one needs `cities` to be directly on a country it is possible to define a calculation:
```elixir
calculate :cities, {:array, :map} do
  load states: :cities
  calculation fn record, _ ->
    Enum.flat_map(record.states, & &1.cities)
  end
end
```
With this `county |> Api.load(:cities)` should work.
