### ISSUE TITLE
Link each function/macro definition to its overarching guides

### ISSUE THREAD

**Issue by RoyalIcing** [ash-project/ash#1491] opened 2024-10-02 02:25 UTC
**Is your feature request related to a problem? Please describe.**

When working on a feature, say an Ash resource for a form, I’ll be adding validations. I might look at the docs for `present`: https://hexdocs.pm/ash/3.4.22/Ash.Resource.Validation.Builtins.html#present/2

**Describe the solution you'd like**

I know talking to Zach and the team there are docs about validation. What would be really handy is a link to those recommended docs against every single function/macro so I don’t have to go hunting for them.

**Describe alternatives you've considered**

Reading all the Ash docs from top to bottom and trying to remember them all. I know even if I did this (which I should), I’d still need to re-read docs to remind me so these links would still be really useful.

**Comment by zachdaniel** [comment] 2024-10-02 02:34
Closing as duplicate of https://github.com/ash-project/ash/issues/1089

I've moved the context there to the general  issue for reworking reference docs. I'm not closing this because its not going to happen, only because its easier for me later if I have the context in a single issue when I actually begin that epic, as one big pass at docs will be better than multiple passes.

**Closed by zachdaniel** 2024-10-02 02:34 UTC
Labels: enhancement, needs review
