### ISSUE TITLE
Ash.CustomExpression behaves differently when used directly by an action versus when wrapped in a calculation

### ISSUE THREAD

**Issue by siassaj** [ash-project/ash#1572] opened 2024-11-02 19:43 UTC
**Describe the bug**
An `Ash.CustomExpression` in a boolean expression behaves differently when used directly in a read action versus when wrapped in a calculation.
```elixir
    read :by_directly_matching_name do
      argument :term, :string do
        allow_nil? false
      end

      filter expr(trigram_word_similarity(name, ^arg(:term)) > 0.2)
    end
    
    #=> SELECT t0."id", t0."name" FROM "my_resource" AS t0 []  
```
vs
```elixir
    calculate :calc_word_similarity, :float, expr(trigram_word_similarity(name, ^arg(:term))) do
      argument :term, :string, allow_nil?: false
    end
    
    read :by_indirectly_matching_name do
      argument :term, :string do
        allow_nil? false
      end

      filter expr(calc_word_similarity(term: ^arg(:term)) > 0.2)
    end
    
    #=> SELECT t0."id", t0."name" FROM "my_resource" AS t0 WHERE ((word_similarity(t0."name"::text, $1))::float > $2::float) ["search_term", 0.2]
```

The details below indicate to me that Ash.Filter.hydrate_refs/2 appear to 'optimise away' boolean expressions in elixir code, rather than preserving them as sql, although that's only a naive guess.

**To Reproduce**

1. implement `lib/expressions/trigram_word_similarity.ex`
```elixir
defmodule MyApp.Expressions.TrigramWordSimilarity do
  use Ash.CustomExpression,
      name: :trigram_word_similarity,
      arguments: [[:string, :string]],
      predicate?: false # setting to true does not seem to change the behaviour observed in this ticket

  def expression(data_layer, [left, right]) when data_layer in [AshPostgres.DataLayer] do
    {:ok, expr(fragment("word_similarity(?, ?)", ^left, ^right))}
  end

  def expression(_data_layer, _args), do: :unknown
end
```

2. Populate `:custom_expressions` configuration option in config/config.exs`
```elixir
config :ash, :custom_expressions, [MyApp.Expressions.TrigramWordSimilarity]
```

3. Implement an Ash resource
```elixir
defmodule MyApp.MyDomain.MyResource do
  use Ash.Resource,
    domain: MyApp.MyDomain,
    data_layer: AshPostgres.DataLayer

  postgres do
    repo MyApp.Repo
    table "my_resource"
  end

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? true
      public? true
    end
  end

  calculations do
    calculate :calc_word_similarity, :float, expr(trigram_word_similarity(name, ^arg(:term))) do
      argument :term, :string, allow_nil?: false
    end
  end

  actions do
    default_accept [:*]
    defaults [:create]

    read :by_indirectly_matching_name do
      argument :term, :string do
        allow_nil? false
      end

      filter expr(calc_word_similarity(term: ^arg(:term)) > 0.2)
    end

    read :by_directly_matching_name do
      argument :term, :string do
        allow_nil? false
      end

      filter expr(trigram_word_similarity(name, ^arg(:term)) > 0.2)
    end
  end
end
```

4. Run the queries
`MyApp.MyDomain.MyResource |> Ash.Query.for_read(:by_directly_matching_name, %{term: "some_term"}) |> Ash.read!();`
and
`MyApp.MyDomain.MyResource |> Ash.Query.for_read(:by_indirectly_matching_name, %{term: "some_term"}) |> Ash.read!();`

**Expected behavior**
The result set & sql generated by both queries to be identical

**Runtime**
 - Elixir version
   1.17.2
 - Erlang version
   Erlang/OTP 27 [erts-15.0.1]
 - OS
   Ubuntu 22.04.5 LTS
 - Ash version
   3.4.39
 - any related extension versions
   ash_postgres: 2.4.12

**Additional context**
Added dbg` statements to `ash/lib/ash/filter/filter.ex#3625`
```elixir
  def do_hydrate_refs(%Call{} = call, context) do
    dbg([call, context])
    resolve_call(call, context) |> dbg
  end
```

Added dbg` statement to `ash/lib/ash/filter/filter.ex#3401
```elixir
  def hydrate_refs(value, context) do
    context =
      context
      |> Map.put_new(:resource, nil)
      |> Map.put_new(:root_resource, context[:resource])
      |> Map.put_new(:public?, false)

    do_hydrate_refs(value, context) |> dbg
  end
```
with the following output
` MyApp.MyDomain.MyResource |> Ash.Query.for_read(:by_directly_matching_name, %{term: "some_term"}) |> Ash.read!()`
=>
```
(ash 3.4.39) lib/ash/filter/filter.ex:3626: Ash.Filter.do_hydrate_refs/2]
[call, context] #=> [
  trigram_word_similarity(name,  "some_term"),
  %{
    resource: MyApp.MyDomain.MyResource,
    data_layer: AshPostgres.DataLayer,
    public?: false,
    relationship_path: [],
    input?: false,
    root_resource: MyApp.MyDomain.MyResource
  }
]

[(ash 3.4.39) lib/ash/filter/filter.ex:3626: Ash.Filter.do_hydrate_refs/2]
[call, context] #=> [
  fragment("word_similarity(?, ?)",  name,  "some_term"),
  %{
    resource: MyApp.MyDomain.MyResource,
    data_layer: AshPostgres.DataLayer,
    public?: false,
    relationship_path: [],
    input?: false,
    root_resource: MyApp.MyDomain.MyResource
  }
]

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, ["word_similarity(?, ?)", name, "some_term"]}

[(ash 3.4.39) lib/ash/filter/filter.ex:3627: Ash.Filter.do_hydrate_refs/2]
resolve_call(call, context) #=> {:ok, fragment("word_similarity(?, ?)", name, "some_term")}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, fragment("word_similarity(?, ?)", name, "some_term")}

[(ash 3.4.39) lib/ash/filter/filter.ex:3627: Ash.Filter.do_hydrate_refs/2]
resolve_call(call, context) #=> {:ok, fragment("word_similarity(?, ?)", name, "some_term")}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, [fragment("word_similarity(?, ?)", name, "some_term"), 0.2]}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, true}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, #Ash.Filter<true>}


19:34:56.688 [debug] QUERY OK source="my_resource" db=0.3ms decode=0.6ms queue=0.4ms idle=70.9ms
SELECT t0."id", t0."name" FROM "my_resource" AS t0 []
```

`MyApp.MyDomain.Myresource |> Ash.Query.for_read(:by_indirectly_matching_name, %{term: "some_term"}) |> Ash.read!()`
=>
```
[(ash 3.4.39) lib/ash/filter/filter.ex:3626: Ash.Filter.do_hydrate_refs/2]
[call, context] #=> [
  calc_word_similarity([term: "some_term"]),
  %{
    resource: MyApp.MyDomain.MyResource,
    public?: false,
    relationship_path: [],
    data_layer: AshPostgres.DataLayer,
    input?: false,
    root_resource: MyApp.MyDomain.MyResource
  }
]

[(ash 3.4.39) lib/ash/filter/filter.ex:3627: Ash.Filter.do_hydrate_refs/2]
resolve_call(call, context) #=> {:ok, calc_word_similarity([term: "some_term"])}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, [calc_word_similarity([term: "some_term"]), 0.2]}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, calc_word_similarity([term: "some_term"]) > 0.2}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, #Ash.Filter<calc_word_similarity([term: "some_term"]) > 0.2>}

[(ash 3.4.39) lib/ash/filter/filter.ex:3626: Ash.Filter.do_hydrate_refs/2]
[call, context] #=> [
  trigram_word_similarity(name,  "some_term"),
  %{
    resource: MyApp.MyDomain.MyResource,
    public?: false,
    root_resource: MyApp.MyDomain.MyResource
  }
]

[(ash 3.4.39) lib/ash/filter/filter.ex:3626: Ash.Filter.do_hydrate_refs/2]
[call, context] #=> [
  fragment("word_similarity(?, ?)",  name,  "some_term"),
  %{
    resource: MyApp.MyDomain.MyResource,
    public?: false,
    relationship_path: [],
    root_resource: MyApp.MyDomain.MyResource
  }
]

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, ["word_similarity(?, ?)", name, "some_term"]}

[(ash 3.4.39) lib/ash/filter/filter.ex:3627: Ash.Filter.do_hydrate_refs/2]
resolve_call(call, context) #=> {:ok, fragment("word_similarity(?, ?)", name, "some_term")}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok, fragment("word_similarity(?, ?)", name, "some_term")}

[(ash 3.4.39) lib/ash/filter/filter.ex:3627: Ash.Filter.do_hydrate_refs/2]
resolve_call(call, context) #=> {:ok, fragment("word_similarity(?, ?)", name, "some_term")}

[(ash 3.4.39) lib/ash/filter/filter.ex:3408: Ash.Filter.hydrate_refs/2]
do_hydrate_refs(value, context) #=> {:ok,
 type(
   fragment("word_similarity(?, ?)", name, "some_term"),
   Ash.Type.Float,
   []
 )}


19:36:46.306 [debug] QUERY OK source="my_resource" db=0.7ms decode=1.2ms queue=0.6ms idle=1290.4ms
SELECT t0."id", t0."name" FROM "my_resource" AS t0 WHERE ((word_similarity(t0."name"::text, $1))::float > $2::float) ["some_term", 0.2]

```

Reworking the boolean expression into the custom expression works as expected, with the 

in the custom expression
```elixir
  def expression(data_layer, [left, right, min_threshold])
      when data_layer in [AshPostgres.DataLayer] do
    {:ok, expr(fragment("word_similarity(?, ?)", ^left, ^right) > ^min_threshold)}
  end
```
in the resource
```elixir
  calculations do
    calculate :name_is_similar_to_term,
              :boolean,
              expr(trigram_word_similarity(name, ^arg(:term), ^arg(:min_threshold))) do
      argument :term, :string, allow_nil?: false
      argument :min_threshold, :float, allow_nil?: false
    end
  end

  actions do
    default_accept [:*]
    defaults [:create]

    read :by_indirectly_matching_name do
      argument :term, :string do
        allow_nil? false
      end

      filter expr(name_is_similar_to_term(term: ^arg(:term), min_threshold: 0.2))
    end

    read :by_directly_matching_name do
      argument :term, :string do
        allow_nil? false
      end

      filter expr(trigram_word_similarity(name, ^arg(:term), 0.2))
    end
  end
```

**Comment by zachdaniel** [comment] 2024-11-03 00:00
I'm unable to reproduce this. I've [added tests ](https://github.com/ash-project/ash_postgres/commit/99acc0f40ce503a7aadecda1ee454b9457396075) that mimic your issue as far as I can tell. I'll close this for now. Please create a reproduction project that illustrates the issue, or alter the tests in `ash_postgres` to reproduce this issue. Only so much I can do without being able to reproduce.

Thank you for your well thought out and detailed issue ❤️

**Comment by siassaj** [comment] 2024-11-04 11:14
@zachdaniel https://github.com/siassaj/ash_issue_1572

**Comment by zachdaniel** [comment] 2024-11-04 17:13
Thank you for the reproduction! It helped me track down the issue very quickly 🙇

**Closed** 2024-11-04 17:13 UTC
Labels: bug, needs review
