### ISSUE TITLE
Api.bulk_create ignore context.data_layer.schema value

### ISSUE THREAD

**Issue by sezaru** [ash-project/ash#818] opened 2024-01-05 14:10 UTC
**Describe the bug**
If you set manually the changeset context data layer schema field to something else, that value will be ignored

**To Reproduce**
In a resource, create a custom create action that will set the schema field:

```elixir
    create :create do
      change fn changeset, _ ->
        Ash.Changeset.set_context(changeset, %{data_layer: %{table: "table", schema: "schema"}})
      end
    end
```

Then, you can just run that action using `bulk_create`.

It will get the following error:

```elixir
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation \"temp_entities\" does not exist\n\n
```

**Expected behavior**
The data_layer `table` field inside the changeset context will work as expected, but it will still use the default `public` schema, ignoring the custom one.

Ash should check for the `schema` field inside the data_layer context and use it when available.

**Runtime**
 - Elixir version 1.16.0
 - Erlang version 26.2.1
 - OS Fedora Silverblue 39
 - Ash version 2.17.20

**Comment by zachdaniel** [comment] 2024-01-05 15:02
Should be fixed in `main`. Please give it a try and let me know.

**Comment by sezaru** [comment] 2024-01-05 15:24
Working great, thanks!

**Comment by sezaru** [comment] 2024-01-08 22:02
I'm reopening this because `Ash.Query` has the exact same issue.

**Comment by zachdaniel** [comment] 2024-01-08 22:03
When you say `Ash.Query` has the same issue, in what context? Calling `Api.read`? How are you calling it?

**Comment by zachdaniel** [comment] 2024-01-08 22:50
This is very strange, because as far as I can tell it works. When I run a query with that context set to a schema it works. Although....does your resource have a hard-coded `"public"` schema in its DSL config?

**Comment by sezaru** [comment] 2024-01-09 00:16
No, I don't set the schema explicitly in this resource

The action I'm using is this one:

```elixir
read :read_test do
      prepare fn query, _ ->
        Ash.Query.set_context(query, %{data_layer: %{table: "temp_entities", schema: "temp"}})
      end
    end
```

One thing that maybe is relevant is that I'm using this read action inside a relationship:

```elixir
  has_one :similar_entity, Entity do
      no_attributes? true

      read_action :read_test

      filter expr(
               full_name == parent(first_grantee_full_name)
             )
    end
```

And I get this error:

```elixir
** (Ash.Error.Unknown) Context: resolving data on load similar_entity

Unknown Error

Context: resolving data on fetch Pacman.Markets.Entity.read_test
* Context: resolving data on fetch Pacman.Markets.Entity.read_test

** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "public.temp_entities" does not exist
```

When I try to load it with `Pacman.Raw.load(records, :similar_entity)`

**Comment by zachdaniel** [comment] 2024-01-09 13:31
Can you try `main`?

**Comment by sezaru** [comment] 2024-01-09 13:46
Just tried it, same issue, it still defaults to `public` schema instead of using the custom one.

**Comment by sezaru** [comment] 2024-01-09 13:52
Also, I saw that you changed the function `maybe_get_resource_query` in the `join.ex` file, so I added some debug messages there just to make sure it was being called, but when I do the `load` call, it never calls that function at all.

**Comment by zachdaniel** [comment] 2024-01-09 13:58
Yeah, okay, so the issue is somewhere in our lateral join query builder. Would it be possible for you to add a test case for this in `ash_postgres`? I don't think I'll have a lot of time to address this, and a test case would make it *much* easier for me.

**Comment by sezaru** [comment] 2024-01-09 16:27
Here is the unit test @zachdaniel https://github.com/sezaru/ash_postgres/tree/add_unit_test_for_lateral_join

**Comment by zachdaniel** [comment] 2024-01-10 13:25
Thank you for the test! This should be fixed in main.

**Closed by zachdaniel** 2024-01-10 13:25 UTC
Labels: bug
