### ISSUE TITLE
Calculation names that end with a "?" cannot be called with the "!" variant.

### ISSUE THREAD

**Issue by apreifsteck** [ash-project/ash#857] opened 2024-01-29 23:26 UTC
**Describe the bug**
Defining a calculation that ends in `?` in the code interface of a resource causes the bang version to fail. E.g: `Resource.is_true?(data)` will return `{:ok, true}`, but `Resource.is_true?!(data)` will raise a function clause error.

**To Reproduce**
```elixir
defmodule Thing.Resource do
  use Ash.Resource

  attributes do
    uuid_primary_key :id
  end

  calculations do
    calculate :is_true?, :boolean, expr(true) 
  end

  code_interface do
    define_for Thing.Api
    define_calculation :is_true?, args: [:_record]
  end
end
```

**Expected behavior**
```
iex(6)> Thing.Resource.is_true?!(%Thing.Resource{})
true
```
**Actual behavior**
```
iex(6)> Thing.Resource.is_true?!(%Thing.Resource{})
** (FunctionClauseError) no function clause matching in Thing.Resource."-inlined-is_true?/2-"/2    
    
    The following arguments were given to Thing.Resource."-inlined-is_true?/2-"/2:
    
        # 1
        false
    
        # 2
        []
    
    (ash_calculation_bug_reproduced 0.1.0) Thing.Resource."-inlined-is_true?/2-"/2
    iex:6: (file)
```

**Runtime**
 - Elixir version
   - 1.15.4
 - Erlang version
   - 26.0.2
 - OS
   - Mac OS Sonoma 14.1.1
 - Ash version
   - 2.14
 - any related extension versions
   - N/A

**Comment by zachdaniel** [comment] 2024-01-30 02:20
Thanks for the report! I won't have time to look into this in the near future I don't think, but this shouldn't be too complex of a fix. Hopefully someone has a chance to take a stab at it, I've marked it as a good first issue :)

**Comment by vonagam** [comment] 2024-01-30 22:04
I think the issue is that in Elixir one should not be able to define or call a method ending with `?!`, it does not get parsed correctly:
```elixir
defmodule Check do 
  def is_good?!, do: :bad
end
```
This will give syntax error. And in the call case you can see that it was parsed like this: 
```elixir
Thing.Resource.is_true?(!(%Thing.Resource{}))
```
That's why it says that the first argument passed into `is_true?` was `false`.

Simplest thing would be to replace question mark with exclamation. But before that the question is if there is any other convention that can be used in such case?

**Comment by zachdaniel** [comment] 2024-01-30 22:08
Ah, right. What we should actually do is for the question mark version, we *strip* the question mark for the non raising version, and leave it in for the raising version. So there never ends up being a `!` version. just `thing` (not raising) and `thing?` (raising)

**Closed** 2024-01-31 20:42 UTC
Labels: bug, good first issue
