### ISSUE TITLE
Raised `Ash.Error.Invalid` error in `update` mutation, with read action having an after_action callback returning error tuple

### ISSUE THREAD

**Issue by moxley** [ash-project/ash#1301] opened 2024-07-11 03:16 UTC
**Describe the bug**

I'm trying to update my codebase to an Ash 2 to 3 upgrade. In one code path (an unhappy path), there is now a raised error when executing an update mutation, where its read action prepares an after_action, which in turn needs to return an error tuple. Either Ash or AshGraphql doesn't handle the error tuple, or maybe I'm not doing it the Ash 3.0 way?

**To Reproduce**

See [this commit](https://github.com/moxley/ash_graphql/commit/ef6460d4814c46854cf7f01ed3d57d3024426dc6#diff-e6e5aa6929dca32a867918e3f15d1510c659f2475b95c26261068ea22f822f46R367) to the ash_graph tests.

1. Define an update mutation
2. For the read action of the update, define a `prepare`. Inside the `prepare`, call `Ash.Query.after_query()`, and have its callback function return an error tuple.
3. Run the mutation.
4. Raises the following error:

```txt
20:00:23.645 [error] 0ec3c77a-5d11-4f8d-9e27-416c39148251: Exception raised while resolving query.

** (Ash.Error.Invalid) Invalid Error

* test error
  (ash 3.1.2) /Users/moxley/work/ash_graphql/deps/splode/lib/splode.ex:277: Ash.Error.to_error/2
  (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
  (ash 3.1.2) /Users/moxley/work/ash_graphql/deps/splode/lib/splode.ex:222: Ash.Error.choose_error/1
  (ash 3.1.2) /Users/moxley/work/ash_graphql/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
  (ash 3.1.2) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
```

**Expected behavior**

The mutation should gracefully return an error in the response. There should be no raised error in the console.

**Runtime**
 - Elixir version 1.17
 - Erlang version 26
 - OS MacOS 1.14
 - Ash version `main`
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment] 2024-07-11 14:17
Okay, so I see the problem, thank you for the reproduction 🙇 

Fixing it will be interesting. The basic problem is that we use `Ash.stream!` to run the query in a bulk context... 🤔 I think what we can do to solve this for the general case is check if `query.limit` is less than batch size, and if so we can build and run the query as normal w/o a raising variant. Will explore.

**Comment by moxley** [comment] 2024-07-11 14:50
> Okay, so I see the problem, thank you for the reproduction 🙇
> 
> Fixing it will be interesting. The basic problem is that we use `Ash.stream!` to run the query in a bulk context... 🤔 I think what we can do to solve this for the general case is check if `query.limit` is less than batch size, and if so we can build and run the query as normal w/o a raising variant. Will explore.

Thank you for investigating this! The Ash v3 upgrade in my app has been a full-time, multi-day project. After this issue is resolved, there are only two remaining issues 🤞

**Comment by zachdaniel** [comment] 2024-07-11 14:56
Latest version of `ash` is now released with the fix. Ash 3.0 was definitely a bigger effort to upgrade than we intended. Luckily there are no big upgrades even anywhere near on the horizon :). If there is a 4.0, it will be minuscule in comparison.

**Closed by zachdaniel** 2024-07-11 14:56 UTC
Labels: bug

**Comment by moxley** [comment] 2024-07-11 15:03
Thanks!

Yeah, I remember the upgrade of Rails from 2 to 3. That was a giant effort to upgrade to.
