### ISSUE TITLE
Add `after_transaction_batch` hook

### ISSUE THREAD

**Issue by yujonglee** [ash-project/ash#1564] opened 2024-10-30 01:36 UTC
**Is your feature request related to a problem? Please describe.**

Currently, `after_batch` runs inside transaction. There's nothing I can do if I want to do some extra work after batch outside of transation.

**Describe the solution you'd like**

Add `after_transaction_batch` hook

**Describe alternatives you've considered**

Use `after_transaction` for individual changeset.

**Comment by zachdaniel** [comment] 2024-10-30 01:41
I've labeled this as "good first issue", but it is actually reasonably complex. Its more like a "good second" or "good third" issue 😆 But its a digestible piece to add and would be very useful :)

**Comment by zachdaniel** [comment] 2024-11-05 13:47
Closing as a duplicate of #1580 (that one refers to both before and after batch hooks)

**Closed by zachdaniel** 2024-11-05 13:47 UTC
Labels: enhancement, good first issue
